import Header from "@/components/layout/Header"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/providers/ThemeProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Header />
                    <div className="flex w-full max-w-screen-xl mx-auto px-4 gap-4">
                        <div className="hidden md:flex md:w-1/3 lg:w-1/4 px-5 py-4">
                            sidebar
                        </div>
                        <div className="md:w-2/3 lg:w-3/4 px-5 py-4">
                            {children}
                        </div>
                        <div className="hidden lg:flex lg:w-1/4 px-5 py-4">
                            sidebar
                        </div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}
