import Header from "@/components/layout/Header"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/providers/ThemeProvider"
import Sidebar from "@/components/layout/sidebar/Sidebar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Header />
                    <div className="flex w-full max-w-screen-xl mx-auto px-4">
                        <div className="hidden md:flex md:w-[250px] h-screen sticky top-0 border-r">
                            <Sidebar />
                        </div>
                        <div className="w-full md:max-w-[56ch] md:px-5 py-4 mt-12">
                            {children}
                        </div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}
